function createplot(X1, Y1, Parent1)
%CREATEPLOT(X1, Y1, Parent1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  PARENT1:  plot parent

%  Auto-generated by MATLAB on 10-Feb-2021 23:45:00

% Create plot
plot(X1,Y1,'DisplayName','Targets - Outputs','Parent',Parent1,'Marker','.',...
    'LineWidth',1.5,...
    'LineStyle','none',...
    'Color',[0 0 1]);

